WeLightProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # url principal
    url(r'^admin/', admin.site.urls),      # url admin
    url(r'^app/', include('app.urls')),    # apunta a las urls de la app
]

app/urls.py
from django.conf.urls import url
from app import views

app_name = "listado_app"

urlpatterns = [
    url(r'^$', views.index, name='read_data'),
    url(r'^create/$',views.createReport, name='create_form'), # Para acceder a la url de creación
    url(r'^edit/(\d{1,10})/$',views.editReport, name='edit_form'), # Para acceder a la url de editar un registro
    url(r'^delete/(\d{1,10})/$',views.deleteReport, name='delete_form'), # Para acceder a la url de eliminar un registro
]

app/models.py
from __future__ import unicode_literals

from django.db import models

# Se ha creado el modelo según el csv
class MonitoringReports(models.Model):
    
    # Atributos del modelo
    id = models.AutoField(primary_key = True)
    date = models.CharField(max_length=100)
    energy = models.FloatField(max_length=20)
    reactive_energy = models.FloatField(max_length=20)
    power = models.FloatField(max_length=20)
    maximeter = models.FloatField(max_length=20)
    reactive_power = models.FloatField(max_length=20)
    voltage = models.FloatField(max_length=20)
    intensity = models.FloatField(max_length=20)
    power_factor = models.FloatField(max_length=20)

app/forms.py
from django import forms
from app.models import MonitoringReports


class ReportForm(forms.ModelForm):
    class Meta:
        model = MonitoringReports
        fields = ['date','energy','reactive_energy','power','maximeter','reactive_power','voltage','intensity','power_factor',]
        

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView
from app.models import MonitoringReports
from app.forms import ReportForm

# Se muestra la información de la tabla completa en la vista principal.
def index(request):
    # Obtener todo el objeto
    read = MonitoringReports.objects.all()
    return render(request, 'index.html', {'read_data': read})


# Crea un registro nuevo
def createReport(request):
    if request.method == 'POST':
        create_form = ReportForm(request.POST)
        if create_form.is_valid(): # Se va todo bien
            create_form.save()
            return redirect('index') # redigirir a la página principal
    else:
        create_form = ReportForm()
    return render(request, 'create_form.html', {'create_form': create_form})


# Sobre un registro ya creado, elimina los valores deseados
def editReport(request, id):
    report = MonitoringReports.objects.get(id = id)
    if request.method == 'GET':
        edit_form = ReportForm(instance = report)
    else:
        edit_form = ReportForm(request.POST, instance = report)
        if edit_form.is_valid():
            edit_form.save()
        return redirect('index')  # redigirir a la página principal
    return render(request, 'create_form.html', {'edit_form': report})


# Elimina un registro
def deleteReport(request,id):
    report = MonitoringReports.objects.get(id = id)
    if request.method == 'POST':
        report.delete()
        return redirect('index')  # redigirir a la página principal
    return render(request,'delete_form.html', {'delete_form': report})

app/templates/create_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Create a record</title>
    {# Cargamos la librería #} {% load bootstrap4 %} {# CSS Bootstrap #} {% bootstrap_css %}
</head>
<h1 style="margin: 10px;"> Record creation form </h1>

<body>
    <form action="" method="post">
        <div style="padding: 30px;">
            {% csrf_token %} {{ create_form.as_p }}
            <button class="btn btn-success" type="submit">Save</button>
        </div>
    </form>
</body>

app/templates/delete_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Delete a record</title>
    {# Cargamos la librería #} {% load bootstrap4 %} {# CSS Bootstrap #} {% bootstrap_css %}
</head>

<h1 style="margin: 10px;"> Are you sure you want to delete the record? </h1>

<body>
    <form action="" method="post">
        <div style="padding: 50px;">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Delete</button>
            <a href="{% url 'index' %}" button class="btn btn-secondary" type="submit">Cancel</a>
        </div>
    </form>
</body>

app/templates/edit_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Create a record</title>
    {# Cargamos la librería #} {% load bootstrap4 %} {# CSS Bootstrap #} {% bootstrap_css %}
</head>
<h1 style="margin: 10px;"> Record creation form </h1>

<body>
    <form action="{% url 'listado_app:edit_form' id=edit_form.instance.id  %}" method="post">
        <div style="padding: 30px;">
            {% csrf_token %} {{ edit_form.as_p }}
            <button class="btn btn-success" type="submit">Save</button>
        </div>
    </form>
</body>

app/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Monitoring reporter</title>
    {# Cargamos la librería #} {% load bootstrap4 %} {# CSS Bootstrap #} {% bootstrap_css %}
</head>

<br>

<h1 style="margin-left: 10px;"> Monitoring report data</h1>
<br>

<body>
    <div style="padding-left: 50px; padding-right: 50px;">
        <a href="{% url 'listado_app:create_form' %}" button class="btn btn-success" type="submit">Create</a>
    </div>

    <br><br>

    <div style="padding-left: 50px; padding-right: 50px;">
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" style="text-align: center;">Nº</th>
                        <th scope="col" style="text-align: center;">Date</th>
                        <th scope="col" style="text-align: center;">Energy</th>
                        <th scope="col" style="text-align: center;">Reactive energy</th>
                        <th scope="col" style="text-align: center;">Power</th>
                        <th scope="col" style="text-align: center;">Maximeter</th>
                        <th scope="col" style="text-align: center;">Reactive power</th>
                        <th scope="col" style="text-align: center;">Voltage</th>
                        <th scope="col" style="text-align: center;">Intensity</th>
                        <th scope="col" style="text-align: center;">Power factor</th>
                        <th scope="col" style="text-align: center;">Actions</th>
                    </tr>
                </thead>
                {% for element in read_data %}
                <tbody>
                    <tr>
                        <td style="text-align: center;">{{ element.id }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.date }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.energy }}</td>
                        <td style="text-align: center;">{{ element.reactive_energy }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.power }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.maximeter }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.reactive_power }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.voltage }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.intensity }}</td style="text-align: center;">
                        <td style="text-align: center;">{{ element.power_factor }}</td style="text-align: center;">
                        <td>
                            <a href="{% url 'listado_app:edit_form' element.id %}" class="btn btn-warning">Edit</a>
                            <a href="{% url 'listado_app:delete_form' element.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</body>